# Домашнее задание "Линейная алгебра. Матрицы".

In [2]:
import numpy as np

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [3]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat2= np.eye(3)
mat3 = mat1+mat2
mat3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [4]:
# каждый элемент 1 массива умножается на соответствующий элемент вектора. Результирующий массив будет иметь форму большей матрицы
np.multiply(mat3, np.array([1, 2, 3]))

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [5]:
# от перестановки множителей результирующий массив не изменится
np.multiply(np.array([1, 2, 3]), mat3)

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [6]:
np.dot(np.array([1, 2, 3]), mat3)

array([31., 38., 45.])

In [7]:
np.transpose(mat3)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [8]:
np.linalg.inv(mat3)

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
# собственные значения
m = np.array([[2, 2], [1, 3]])
np.linalg.eigvals(m)

array([1., 4.])

In [ ]:
# собственные значения и собственные вектора
np.linalg.eig(m)

EigResult(eigenvalues=array([1., 4.]), eigenvectors=array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]]))

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [113]:
mat4 = np.array([[-1.58404, -0.9, -0.8], [-0.05, -1, -0.5], [-0.73, -0.99, 0]])

In [115]:
np.linalg.matrix_rank(mat4)

np.int64(3)

In [114]:
np.linalg.det(mat4)

np.float64(0.9999997999999999)